#!/bin/bash
#name=`basename $0`
name=`basename $0`
echo $name
if [ $name = "addem" ]
then
    total=$[ $1 + $2 ]
elif [ $name = "multem" ]
then 
    total=$[ $1 * $2 ]
fi
echo The calculated value is $total
